### ISSUE TITLE
Avaliação 

### ISSUE THREAD

**Issue by agualbbus** [CRFLuiz/concretejs#1]
**Pontos negativos:**

- Readme vazio.
- node_modules ignorado no .gitignore mas commitado no repositório.
- Mistura de inglês com português.
- código comentado que poderia ser apagado.
- código haduken.
- parece que guarda token na base de dados (não é stateless).
- importação de libs não utilizadas. 
- nodemon não esta listado como devDependencie

**Pontos positivos:**

- Cobertura de tests.
-  uso de jshint.
-  middleware de validação, porem faria mas sentido se a validação do token fosse stateless.
- bom uso de promises.

**Comment by CRFLuiz** [comment]
https://github.com/CRFLuiz/concretejs/issues/1#issue-463287348
Bom dia. Peço desculpas pela demora. Corrigi os pontos negativos relacionados ao readme, node_modules, comentários excessivos, libs importadas sem serem utilizadas e o nodemon listado nas dependencias de desenvolvimento.
Em relação aos erros não corrigidos, cito:
**Mistura de inglês com português**: correção em andamento.
**Código hadouken**: ainda não consigo enxergar uma solução melhor tendo em vista que eu precise trabalhar com transaction. Seguirei buscando alternativas melhores.
**Token armazenado no banco de dados**: pensei em fazer sem estado, mas no e-mail que recebi com o desafio estava pedindo que, na busca de usuário, o token passado no Header da requisição fosse comparado com o token do usuário buscado no modelo. Gostaria de saber se eu realmente entendi o e-mail errado e, em caso afirmativo, alterarei imediatamente.
Desde já, agradeço.

**Comment by CRFLuiz** [comment]
https://github.com/CRFLuiz/concretejs/issues/1#issue-463287348
Bom dia. Peço desculpas pela demora. Corrigi os pontos negativos relacionados ao **readme**, **node_modules**, **comentários excessivos**, **libs importadas sem serem utilizadas** e o **nodemon listado nas dependencias de desenvolvimento**.
Em relação aos erros não corrigidos, cito:
**Mistura de inglês com português:** correção em andamento.
**Código hadouken:** ainda não consigo enxergar uma solução melhor tendo em vista que eu precise trabalhar com transaction. Seguirei buscando alternativas melhores.
**Token armazenado no banco de dados:** pensei em fazer sem estado, mas no e-mail que recebi com o desafio estava pedindo que, na busca de usuário, o token passado no Header da requisição fosse comparado com o token do usuário buscado no modelo. Gostaria de saber se eu realmente entendi o e-mail errado e, em caso afirmativo, alterarei imediatamente. Desde já, agradeço.
Agradeço também pelas informações dos pontos positivos. O foco é sempre aprender mais.
